version: '3.8'

networks:
  divar_app:

volumes:
  db_data:
  cache_data:
  pmadata:
  esdata:

services:
  app:
    build: 
      context: ./
      dockerfile: ./docker/php/Dockerfile
    image: divar-app
    container_name: divar-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - redis-cache
      - mariadb
    networks:
      - divar_app

  mariadb:
    image: mariadb:10.5.9
    container_name: divar-db
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - db_data:/var/lib/mysql

    environment:
      MYSQL_DATABASE: divar_db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - divar_app

  nginx:
    image: nginx:1.23.3-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - app
      - mariadb
    networks:
      - divar_app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_PMADB: 1
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    restart: always
    depends_on:
      - mariadb
    ports:
      - "80:80"
    volumes:
      - "pmadata:/etc/phpmyadmin/config.user.inc.php"
    networks:
      - divar_app
    links:
      - mariadb

  redis-cache:
    image: redis:alpine
    container_name: divar-cache
    hostname: redis
    volumes:
      - cache_data:/data
    ports:
      - "6188:6379"
    networks:
        - divar_app

  # elasticsearch:
  #   container_name: elasticsearch
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
  #   restart: always
  #   environment:
  #     - xpack.security.enabled=false
  #     - "discovery.type=single-node"
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data
  #   networks:
  #     - divar_app
  #   ports:
  #     - 9200:9200

  # kibana:
  #   container_name: kibana
  #   image: docker.elastic.co/kibana/kibana:8.7.0
  #   restart: always
  #   environment:
  #     - ELASTICSEARCH_HOSTS="${ELASTICSEARCH_HOST}"
  #   networks:
  #     - divar_app
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - 5601:5601

  nextjs:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    image: nextjs
    container_name: nextjs
    ports:
      - "3000:3000"
    volumes:
      - ./public/front/:/app
    networks:
      - divar_app
