import { Providers } from "./GlobalRedux/provider";
import "./globals.css";
import type { Metadata } from "next";
import { useSelector } from "react-redux";
import Navbar from "./components/Navbar/Index";
import { RootState } from "./GlobalRedux/store";
import Overlay from "./components/Overlay";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: {
        icon: "/app/icon.png",
    },
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const isSearchOpen = useSelector(
        (state: RootState) => state.global.isSearchOpen
    );
    const isCityOpen = useSelector(
        (state: RootState) => state.global.isCityOpen
    );
    return (
        <html lang="en" dir="rtl">
            <body>
                <Providers>
                    {isSearchOpen && (
                        <Overlay top={66} left={0} isOpen={true} />
                    )}
                    {isCityOpen && <Overlay top={0} left={0} isOpen={true} />}
                    <Navbar />
                    {children}
                </Providers>
            </body>
        </html>
    );
}
