import "./globals.css";
import { Providers } from "@/app/GlobalRedux/provider";
import type { Metadata } from "next";
import LayoutContent from "@/app/LayoutContent";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: {
        icon: "/app/icon.png",
    },
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" dir="rtl">
            <body>
                <Providers>
                    <main className="max-w-screen-xl mx-auto py-20 px-2">
                        <LayoutContent />
                        {children}
                    </main>
                </Providers>
            </body>
        </html>
    );
}
